version: "3.8"

services:
  postgres:
    build:
      ./
    image: postgres
    ports:
      - 5432:5432
    volumes:
    - ./postgres_data:/var/lib/postgres
    environment:
      - POSTGRES_PASSWORD=root